server:
  port: 9999
  profiles:
    active: chaos-monkey

chaos:
  monkey:
    enabled: true
    watcher:
      service: false
      controller: false
      repository: false
      restController: true
    assaults:
      level: 1
      latencyActive: true
      latencyRangeStart: 500
      latencyRangeEnd: 2000
      exceptionsActive: false